{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_pytest/demo3.py:19: Exception"}, "start": 1609854401857, "stop": 1609854401858, "uuid": "16540058-5bde-4264-a06e-de469941665b", "historyId": "f0919361a7423e43d51d54c40a12a4eb", "testCaseId": "5a276fb0431e6e2d439299650b55ba69", "fullName": "test_pytest.demo3#test_broken", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "demo3"}, {"name": "host", "value": "AmydeAir"}, {"name": "thread", "value": "85585-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.demo3"}]}